name: Creating Spring boot native
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build with Maven
        run: |
          echo "Building Native Spring API"
          mvn spring-boot:build-image --file pom.xml -s settings.xml
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push to Registry
        run: |
          docker tag docker.io/library/rest-service-complete:0.0.1-SNAPSHOT ghcr.io/c3s4rfred/rest-service-complete:latest
          docker push ghcr.io/c3s4rfred/rest-service-complete:latest
